# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_ADMINREQUESTTYPE = descriptor.EnumDescriptor(
  name='AdminRequestType',
  full_name='voldemort.AdminRequestType',
  filename='AdminRequestType',
  values=[
    descriptor.EnumValueDescriptor(
      name='GET_METADATA', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UPDATE_METADATA', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UPDATE_PARTITION_ENTRIES', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FETCH_PARTITION_ENTRIES', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DELETE_PARTITION_ENTRIES', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INITIATE_FETCH_AND_UPDATE', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ASYNC_OPERATION_STATUS', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INITIATE_REBALANCE_NODE', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ASYNC_OPERATION_STOP', index=8, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ASYNC_OPERATION_LIST', index=9, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TRUNCATE_ENTRIES', index=10, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ADD_STORE', index=11, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DELETE_STORE', index=12, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FETCH_STORE', index=13, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SWAP_STORE', index=14, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ROLLBACK_STORE', index=15, number=15,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GET_RO_MAX_VERSION', index=16, number=16,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GET_RO_CURRENT_VERSION', index=17, number=17,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FETCH_PARTITION_FILES', index=18, number=18,
      options=None,
      type=None),
  ],
  options=None,
)


GET_METADATA = 0
UPDATE_METADATA = 1
UPDATE_PARTITION_ENTRIES = 2
FETCH_PARTITION_ENTRIES = 3
DELETE_PARTITION_ENTRIES = 4
INITIATE_FETCH_AND_UPDATE = 5
ASYNC_OPERATION_STATUS = 6
INITIATE_REBALANCE_NODE = 7
ASYNC_OPERATION_STOP = 8
ASYNC_OPERATION_LIST = 9
TRUNCATE_ENTRIES = 10
ADD_STORE = 11
DELETE_STORE = 12
FETCH_STORE = 13
SWAP_STORE = 14
ROLLBACK_STORE = 15
GET_RO_MAX_VERSION = 16
GET_RO_CURRENT_VERSION = 17
FETCH_PARTITION_FILES = 18



_GETMETADATAREQUEST = descriptor.Descriptor(
  name='GetMetadataRequest',
  full_name='voldemort.GetMetadataRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='voldemort.GetMetadataRequest.key', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_GETMETADATARESPONSE = descriptor.Descriptor(
  name='GetMetadataResponse',
  full_name='voldemort.GetMetadataResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='voldemort.GetMetadataResponse.version', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.GetMetadataResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_UPDATEMETADATAREQUEST = descriptor.Descriptor(
  name='UpdateMetadataRequest',
  full_name='voldemort.UpdateMetadataRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='voldemort.UpdateMetadataRequest.key', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='versioned', full_name='voldemort.UpdateMetadataRequest.versioned', index=1,
      number=2, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_UPDATEMETADATARESPONSE = descriptor.Descriptor(
  name='UpdateMetadataResponse',
  full_name='voldemort.UpdateMetadataResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.UpdateMetadataResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PARTITIONENTRY = descriptor.Descriptor(
  name='PartitionEntry',
  full_name='voldemort.PartitionEntry',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='voldemort.PartitionEntry.key', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='versioned', full_name='voldemort.PartitionEntry.versioned', index=1,
      number=2, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_UPDATEPARTITIONENTRIESREQUEST = descriptor.Descriptor(
  name='UpdatePartitionEntriesRequest',
  full_name='voldemort.UpdatePartitionEntriesRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='store', full_name='voldemort.UpdatePartitionEntriesRequest.store', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='partition_entry', full_name='voldemort.UpdatePartitionEntriesRequest.partition_entry', index=1,
      number=2, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filter', full_name='voldemort.UpdatePartitionEntriesRequest.filter', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_UPDATEPARTITIONENTRIESRESPONSE = descriptor.Descriptor(
  name='UpdatePartitionEntriesResponse',
  full_name='voldemort.UpdatePartitionEntriesResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.UpdatePartitionEntriesResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_VOLDEMORTFILTER = descriptor.Descriptor(
  name='VoldemortFilter',
  full_name='voldemort.VoldemortFilter',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='voldemort.VoldemortFilter.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='voldemort.VoldemortFilter.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_FETCHPARTITIONFILESREQUEST = descriptor.Descriptor(
  name='FetchPartitionFilesRequest',
  full_name='voldemort.FetchPartitionFilesRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='partitions', full_name='voldemort.FetchPartitionFilesRequest.partitions', index=0,
      number=1, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='store', full_name='voldemort.FetchPartitionFilesRequest.store', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_FETCHPARTITIONENTRIESREQUEST = descriptor.Descriptor(
  name='FetchPartitionEntriesRequest',
  full_name='voldemort.FetchPartitionEntriesRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='partitions', full_name='voldemort.FetchPartitionEntriesRequest.partitions', index=0,
      number=1, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='store', full_name='voldemort.FetchPartitionEntriesRequest.store', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filter', full_name='voldemort.FetchPartitionEntriesRequest.filter', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fetch_values', full_name='voldemort.FetchPartitionEntriesRequest.fetch_values', index=3,
      number=4, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fetch_master_entries', full_name='voldemort.FetchPartitionEntriesRequest.fetch_master_entries', index=4,
      number=5, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_FETCHPARTITIONENTRIESRESPONSE = descriptor.Descriptor(
  name='FetchPartitionEntriesResponse',
  full_name='voldemort.FetchPartitionEntriesResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='partition_entry', full_name='voldemort.FetchPartitionEntriesResponse.partition_entry', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='key', full_name='voldemort.FetchPartitionEntriesResponse.key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.FetchPartitionEntriesResponse.error', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_DELETEPARTITIONENTRIESREQUEST = descriptor.Descriptor(
  name='DeletePartitionEntriesRequest',
  full_name='voldemort.DeletePartitionEntriesRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='store', full_name='voldemort.DeletePartitionEntriesRequest.store', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='partitions', full_name='voldemort.DeletePartitionEntriesRequest.partitions', index=1,
      number=2, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filter', full_name='voldemort.DeletePartitionEntriesRequest.filter', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_DELETEPARTITIONENTRIESRESPONSE = descriptor.Descriptor(
  name='DeletePartitionEntriesResponse',
  full_name='voldemort.DeletePartitionEntriesResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='count', full_name='voldemort.DeletePartitionEntriesResponse.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.DeletePartitionEntriesResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_INITIATEFETCHANDUPDATEREQUEST = descriptor.Descriptor(
  name='InitiateFetchAndUpdateRequest',
  full_name='voldemort.InitiateFetchAndUpdateRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='node_id', full_name='voldemort.InitiateFetchAndUpdateRequest.node_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='partitions', full_name='voldemort.InitiateFetchAndUpdateRequest.partitions', index=1,
      number=2, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='store', full_name='voldemort.InitiateFetchAndUpdateRequest.store', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filter', full_name='voldemort.InitiateFetchAndUpdateRequest.filter', index=3,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_readonly', full_name='voldemort.InitiateFetchAndUpdateRequest.is_readonly', index=4,
      number=5, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ASYNCOPERATIONSTATUSREQUEST = descriptor.Descriptor(
  name='AsyncOperationStatusRequest',
  full_name='voldemort.AsyncOperationStatusRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='request_id', full_name='voldemort.AsyncOperationStatusRequest.request_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ASYNCOPERATIONSTOPREQUEST = descriptor.Descriptor(
  name='AsyncOperationStopRequest',
  full_name='voldemort.AsyncOperationStopRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='request_id', full_name='voldemort.AsyncOperationStopRequest.request_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ASYNCOPERATIONSTOPRESPONSE = descriptor.Descriptor(
  name='AsyncOperationStopResponse',
  full_name='voldemort.AsyncOperationStopResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.AsyncOperationStopResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ASYNCOPERATIONLISTREQUEST = descriptor.Descriptor(
  name='AsyncOperationListRequest',
  full_name='voldemort.AsyncOperationListRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='request_id', full_name='voldemort.AsyncOperationListRequest.request_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='show_complete', full_name='voldemort.AsyncOperationListRequest.show_complete', index=1,
      number=2, type=8, cpp_type=7, label=2,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ASYNCOPERATIONLISTRESPONSE = descriptor.Descriptor(
  name='AsyncOperationListResponse',
  full_name='voldemort.AsyncOperationListResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='request_ids', full_name='voldemort.AsyncOperationListResponse.request_ids', index=0,
      number=1, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.AsyncOperationListResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ROSTOREVERSIONMAP = descriptor.Descriptor(
  name='ROStoreVersionMap',
  full_name='voldemort.ROStoreVersionMap',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='store_name', full_name='voldemort.ROStoreVersionMap.store_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='push_version', full_name='voldemort.ROStoreVersionMap.push_version', index=1,
      number=2, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_INITIATEREBALANCENODEREQUEST = descriptor.Descriptor(
  name='InitiateRebalanceNodeRequest',
  full_name='voldemort.InitiateRebalanceNodeRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='stealer_id', full_name='voldemort.InitiateRebalanceNodeRequest.stealer_id', index=0,
      number=2, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='donor_id', full_name='voldemort.InitiateRebalanceNodeRequest.donor_id', index=1,
      number=3, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='partitions', full_name='voldemort.InitiateRebalanceNodeRequest.partitions', index=2,
      number=4, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attempt', full_name='voldemort.InitiateRebalanceNodeRequest.attempt', index=3,
      number=5, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='deletePartitions', full_name='voldemort.InitiateRebalanceNodeRequest.deletePartitions', index=4,
      number=6, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='unbalanced_store', full_name='voldemort.InitiateRebalanceNodeRequest.unbalanced_store', index=5,
      number=7, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stealMasterPartitions', full_name='voldemort.InitiateRebalanceNodeRequest.stealMasterPartitions', index=6,
      number=8, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ASYNCOPERATIONSTATUSRESPONSE = descriptor.Descriptor(
  name='AsyncOperationStatusResponse',
  full_name='voldemort.AsyncOperationStatusResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='request_id', full_name='voldemort.AsyncOperationStatusResponse.request_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='voldemort.AsyncOperationStatusResponse.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='voldemort.AsyncOperationStatusResponse.status', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='complete', full_name='voldemort.AsyncOperationStatusResponse.complete', index=3,
      number=4, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.AsyncOperationStatusResponse.error', index=4,
      number=5, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TRUNCATEENTRIESREQUEST = descriptor.Descriptor(
  name='TruncateEntriesRequest',
  full_name='voldemort.TruncateEntriesRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='store', full_name='voldemort.TruncateEntriesRequest.store', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TRUNCATEENTRIESRESPONSE = descriptor.Descriptor(
  name='TruncateEntriesResponse',
  full_name='voldemort.TruncateEntriesResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.TruncateEntriesResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ADDSTOREREQUEST = descriptor.Descriptor(
  name='AddStoreRequest',
  full_name='voldemort.AddStoreRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='storeDefinition', full_name='voldemort.AddStoreRequest.storeDefinition', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ADDSTORERESPONSE = descriptor.Descriptor(
  name='AddStoreResponse',
  full_name='voldemort.AddStoreResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.AddStoreResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_DELETESTOREREQUEST = descriptor.Descriptor(
  name='DeleteStoreRequest',
  full_name='voldemort.DeleteStoreRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='storeName', full_name='voldemort.DeleteStoreRequest.storeName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_DELETESTORERESPONSE = descriptor.Descriptor(
  name='DeleteStoreResponse',
  full_name='voldemort.DeleteStoreResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.DeleteStoreResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_FETCHSTOREREQUEST = descriptor.Descriptor(
  name='FetchStoreRequest',
  full_name='voldemort.FetchStoreRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='store_name', full_name='voldemort.FetchStoreRequest.store_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='store_dir', full_name='voldemort.FetchStoreRequest.store_dir', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='push_version', full_name='voldemort.FetchStoreRequest.push_version', index=2,
      number=3, type=3, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SWAPSTOREREQUEST = descriptor.Descriptor(
  name='SwapStoreRequest',
  full_name='voldemort.SwapStoreRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='store_name', full_name='voldemort.SwapStoreRequest.store_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='store_dir', full_name='voldemort.SwapStoreRequest.store_dir', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SWAPSTORERESPONSE = descriptor.Descriptor(
  name='SwapStoreResponse',
  full_name='voldemort.SwapStoreResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.SwapStoreResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ROLLBACKSTOREREQUEST = descriptor.Descriptor(
  name='RollbackStoreRequest',
  full_name='voldemort.RollbackStoreRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='store_name', full_name='voldemort.RollbackStoreRequest.store_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='push_version', full_name='voldemort.RollbackStoreRequest.push_version', index=1,
      number=2, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ROLLBACKSTORERESPONSE = descriptor.Descriptor(
  name='RollbackStoreResponse',
  full_name='voldemort.RollbackStoreResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.RollbackStoreResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_GETROMAXVERSIONREQUEST = descriptor.Descriptor(
  name='GetROMaxVersionRequest',
  full_name='voldemort.GetROMaxVersionRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='store_name', full_name='voldemort.GetROMaxVersionRequest.store_name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_GETROMAXVERSIONRESPONSE = descriptor.Descriptor(
  name='GetROMaxVersionResponse',
  full_name='voldemort.GetROMaxVersionResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ro_store_versions', full_name='voldemort.GetROMaxVersionResponse.ro_store_versions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.GetROMaxVersionResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_GETROCURRENTVERSIONREQUEST = descriptor.Descriptor(
  name='GetROCurrentVersionRequest',
  full_name='voldemort.GetROCurrentVersionRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='store_name', full_name='voldemort.GetROCurrentVersionRequest.store_name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_GETROCURRENTVERSIONRESPONSE = descriptor.Descriptor(
  name='GetROCurrentVersionResponse',
  full_name='voldemort.GetROCurrentVersionResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ro_store_versions', full_name='voldemort.GetROCurrentVersionResponse.ro_store_versions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.GetROCurrentVersionResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_VOLDEMORTADMINREQUEST = descriptor.Descriptor(
  name='VoldemortAdminRequest',
  full_name='voldemort.VoldemortAdminRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='voldemort.VoldemortAdminRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='get_metadata', full_name='voldemort.VoldemortAdminRequest.get_metadata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='update_metadata', full_name='voldemort.VoldemortAdminRequest.update_metadata', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='update_partition_entries', full_name='voldemort.VoldemortAdminRequest.update_partition_entries', index=3,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fetch_partition_entries', full_name='voldemort.VoldemortAdminRequest.fetch_partition_entries', index=4,
      number=5, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='delete_partition_entries', full_name='voldemort.VoldemortAdminRequest.delete_partition_entries', index=5,
      number=6, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='initiate_fetch_and_update', full_name='voldemort.VoldemortAdminRequest.initiate_fetch_and_update', index=6,
      number=7, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='async_operation_status', full_name='voldemort.VoldemortAdminRequest.async_operation_status', index=7,
      number=8, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='initiate_rebalance_node', full_name='voldemort.VoldemortAdminRequest.initiate_rebalance_node', index=8,
      number=9, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='async_operation_stop', full_name='voldemort.VoldemortAdminRequest.async_operation_stop', index=9,
      number=10, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='async_operation_list', full_name='voldemort.VoldemortAdminRequest.async_operation_list', index=10,
      number=11, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='truncate_entries', full_name='voldemort.VoldemortAdminRequest.truncate_entries', index=11,
      number=12, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='add_store', full_name='voldemort.VoldemortAdminRequest.add_store', index=12,
      number=13, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='delete_store', full_name='voldemort.VoldemortAdminRequest.delete_store', index=13,
      number=14, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fetch_store', full_name='voldemort.VoldemortAdminRequest.fetch_store', index=14,
      number=15, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='swap_store', full_name='voldemort.VoldemortAdminRequest.swap_store', index=15,
      number=16, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rollback_store', full_name='voldemort.VoldemortAdminRequest.rollback_store', index=16,
      number=17, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='get_ro_max_version', full_name='voldemort.VoldemortAdminRequest.get_ro_max_version', index=17,
      number=18, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='get_ro_current_version', full_name='voldemort.VoldemortAdminRequest.get_ro_current_version', index=18,
      number=19, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fetch_partition_files', full_name='voldemort.VoldemortAdminRequest.fetch_partition_files', index=19,
      number=20, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import voldemort_client_pb2

_GETMETADATARESPONSE.fields_by_name['version'].message_type = voldemort_client_pb2._VERSIONED
_GETMETADATARESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_UPDATEMETADATAREQUEST.fields_by_name['versioned'].message_type = voldemort_client_pb2._VERSIONED
_UPDATEMETADATARESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_PARTITIONENTRY.fields_by_name['versioned'].message_type = voldemort_client_pb2._VERSIONED
_UPDATEPARTITIONENTRIESREQUEST.fields_by_name['partition_entry'].message_type = _PARTITIONENTRY
_UPDATEPARTITIONENTRIESREQUEST.fields_by_name['filter'].message_type = _VOLDEMORTFILTER
_UPDATEPARTITIONENTRIESRESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_FETCHPARTITIONENTRIESREQUEST.fields_by_name['filter'].message_type = _VOLDEMORTFILTER
_FETCHPARTITIONENTRIESRESPONSE.fields_by_name['partition_entry'].message_type = _PARTITIONENTRY
_FETCHPARTITIONENTRIESRESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_DELETEPARTITIONENTRIESREQUEST.fields_by_name['filter'].message_type = _VOLDEMORTFILTER
_DELETEPARTITIONENTRIESRESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_INITIATEFETCHANDUPDATEREQUEST.fields_by_name['filter'].message_type = _VOLDEMORTFILTER
_ASYNCOPERATIONSTOPRESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_ASYNCOPERATIONLISTRESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_ASYNCOPERATIONSTATUSRESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_TRUNCATEENTRIESRESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_ADDSTORERESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_DELETESTORERESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_SWAPSTORERESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_ROLLBACKSTORERESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_GETROMAXVERSIONRESPONSE.fields_by_name['ro_store_versions'].message_type = _ROSTOREVERSIONMAP
_GETROMAXVERSIONRESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_GETROCURRENTVERSIONRESPONSE.fields_by_name['ro_store_versions'].message_type = _ROSTOREVERSIONMAP
_GETROCURRENTVERSIONRESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_VOLDEMORTADMINREQUEST.fields_by_name['type'].enum_type = _ADMINREQUESTTYPE
_VOLDEMORTADMINREQUEST.fields_by_name['get_metadata'].message_type = _GETMETADATAREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['update_metadata'].message_type = _UPDATEMETADATAREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['update_partition_entries'].message_type = _UPDATEPARTITIONENTRIESREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['fetch_partition_entries'].message_type = _FETCHPARTITIONENTRIESREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['delete_partition_entries'].message_type = _DELETEPARTITIONENTRIESREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['initiate_fetch_and_update'].message_type = _INITIATEFETCHANDUPDATEREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['async_operation_status'].message_type = _ASYNCOPERATIONSTATUSREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['initiate_rebalance_node'].message_type = _INITIATEREBALANCENODEREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['async_operation_stop'].message_type = _ASYNCOPERATIONSTOPREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['async_operation_list'].message_type = _ASYNCOPERATIONLISTREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['truncate_entries'].message_type = _TRUNCATEENTRIESREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['add_store'].message_type = _ADDSTOREREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['delete_store'].message_type = _DELETESTOREREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['fetch_store'].message_type = _FETCHSTOREREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['swap_store'].message_type = _SWAPSTOREREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['rollback_store'].message_type = _ROLLBACKSTOREREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['get_ro_max_version'].message_type = _GETROMAXVERSIONREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['get_ro_current_version'].message_type = _GETROCURRENTVERSIONREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['fetch_partition_files'].message_type = _FETCHPARTITIONFILESREQUEST

class GetMetadataRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETMETADATAREQUEST

class GetMetadataResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETMETADATARESPONSE

class UpdateMetadataRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATEMETADATAREQUEST

class UpdateMetadataResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATEMETADATARESPONSE

class PartitionEntry(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARTITIONENTRY

class UpdatePartitionEntriesRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATEPARTITIONENTRIESREQUEST

class UpdatePartitionEntriesResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATEPARTITIONENTRIESRESPONSE

class VoldemortFilter(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VOLDEMORTFILTER

class FetchPartitionFilesRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FETCHPARTITIONFILESREQUEST

class FetchPartitionEntriesRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FETCHPARTITIONENTRIESREQUEST

class FetchPartitionEntriesResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FETCHPARTITIONENTRIESRESPONSE

class DeletePartitionEntriesRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEPARTITIONENTRIESREQUEST

class DeletePartitionEntriesResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEPARTITIONENTRIESRESPONSE

class InitiateFetchAndUpdateRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INITIATEFETCHANDUPDATEREQUEST

class AsyncOperationStatusRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ASYNCOPERATIONSTATUSREQUEST

class AsyncOperationStopRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ASYNCOPERATIONSTOPREQUEST

class AsyncOperationStopResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ASYNCOPERATIONSTOPRESPONSE

class AsyncOperationListRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ASYNCOPERATIONLISTREQUEST

class AsyncOperationListResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ASYNCOPERATIONLISTRESPONSE

class ROStoreVersionMap(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROSTOREVERSIONMAP

class InitiateRebalanceNodeRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INITIATEREBALANCENODEREQUEST

class AsyncOperationStatusResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ASYNCOPERATIONSTATUSRESPONSE

class TruncateEntriesRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRUNCATEENTRIESREQUEST

class TruncateEntriesResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRUNCATEENTRIESRESPONSE

class AddStoreRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDSTOREREQUEST

class AddStoreResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDSTORERESPONSE

class DeleteStoreRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETESTOREREQUEST

class DeleteStoreResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETESTORERESPONSE

class FetchStoreRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FETCHSTOREREQUEST

class SwapStoreRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SWAPSTOREREQUEST

class SwapStoreResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SWAPSTORERESPONSE

class RollbackStoreRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROLLBACKSTOREREQUEST

class RollbackStoreResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROLLBACKSTORERESPONSE

class GetROMaxVersionRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETROMAXVERSIONREQUEST

class GetROMaxVersionResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETROMAXVERSIONRESPONSE

class GetROCurrentVersionRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETROCURRENTVERSIONREQUEST

class GetROCurrentVersionResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETROCURRENTVERSIONRESPONSE

class VoldemortAdminRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VOLDEMORTADMINREQUEST

