# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_ADMINREQUESTTYPE = descriptor.EnumDescriptor(
  name='AdminRequestType',
  full_name='voldemort.AdminRequestType',
  filename='AdminRequestType',
  values=[
    descriptor.EnumValueDescriptor(
      name='GET_METADATA', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UPDATE_METADATA', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UPDATE_PARTITION_ENTRIES', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FETCH_PARTITION_ENTRIES', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DELETE_PARTITION_ENTRIES', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INITIATE_FETCH_AND_UPDATE', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ASYNC_OPERATION_STATUS', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INITIATE_REBALANCE_NODE', index=7, number=7,
      options=None,
      type=None),
  ],
  options=None,
)


GET_METADATA = 0
UPDATE_METADATA = 1
UPDATE_PARTITION_ENTRIES = 2
FETCH_PARTITION_ENTRIES = 3
DELETE_PARTITION_ENTRIES = 4
INITIATE_FETCH_AND_UPDATE = 5
ASYNC_OPERATION_STATUS = 6
INITIATE_REBALANCE_NODE = 7



_GETMETADATAREQUEST = descriptor.Descriptor(
  name='GetMetadataRequest',
  full_name='voldemort.GetMetadataRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='voldemort.GetMetadataRequest.key', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_GETMETADATARESPONSE = descriptor.Descriptor(
  name='GetMetadataResponse',
  full_name='voldemort.GetMetadataResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='voldemort.GetMetadataResponse.version', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.GetMetadataResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_UPDATEMETADATAREQUEST = descriptor.Descriptor(
  name='UpdateMetadataRequest',
  full_name='voldemort.UpdateMetadataRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='voldemort.UpdateMetadataRequest.key', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='versioned', full_name='voldemort.UpdateMetadataRequest.versioned', index=1,
      number=2, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_UPDATEMETADATARESPONSE = descriptor.Descriptor(
  name='UpdateMetadataResponse',
  full_name='voldemort.UpdateMetadataResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.UpdateMetadataResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PARTITIONENTRY = descriptor.Descriptor(
  name='PartitionEntry',
  full_name='voldemort.PartitionEntry',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='voldemort.PartitionEntry.key', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='versioned', full_name='voldemort.PartitionEntry.versioned', index=1,
      number=2, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_UPDATEPARTITIONENTRIESREQUEST = descriptor.Descriptor(
  name='UpdatePartitionEntriesRequest',
  full_name='voldemort.UpdatePartitionEntriesRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='store', full_name='voldemort.UpdatePartitionEntriesRequest.store', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='partition_entry', full_name='voldemort.UpdatePartitionEntriesRequest.partition_entry', index=1,
      number=2, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filter', full_name='voldemort.UpdatePartitionEntriesRequest.filter', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_UPDATEPARTITIONENTRIESRESPONSE = descriptor.Descriptor(
  name='UpdatePartitionEntriesResponse',
  full_name='voldemort.UpdatePartitionEntriesResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.UpdatePartitionEntriesResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_VOLDEMORTFILTER = descriptor.Descriptor(
  name='VoldemortFilter',
  full_name='voldemort.VoldemortFilter',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='voldemort.VoldemortFilter.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='voldemort.VoldemortFilter.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_FETCHPARTITIONENTRIESREQUEST = descriptor.Descriptor(
  name='FetchPartitionEntriesRequest',
  full_name='voldemort.FetchPartitionEntriesRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='partitions', full_name='voldemort.FetchPartitionEntriesRequest.partitions', index=0,
      number=1, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='store', full_name='voldemort.FetchPartitionEntriesRequest.store', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filter', full_name='voldemort.FetchPartitionEntriesRequest.filter', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fetch_values', full_name='voldemort.FetchPartitionEntriesRequest.fetch_values', index=3,
      number=4, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_FETCHPARTITIONENTRIESRESPONSE = descriptor.Descriptor(
  name='FetchPartitionEntriesResponse',
  full_name='voldemort.FetchPartitionEntriesResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='partition_entry', full_name='voldemort.FetchPartitionEntriesResponse.partition_entry', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='key', full_name='voldemort.FetchPartitionEntriesResponse.key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.FetchPartitionEntriesResponse.error', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_DELETEPARTITIONENTRIESREQUEST = descriptor.Descriptor(
  name='DeletePartitionEntriesRequest',
  full_name='voldemort.DeletePartitionEntriesRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='store', full_name='voldemort.DeletePartitionEntriesRequest.store', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='partitions', full_name='voldemort.DeletePartitionEntriesRequest.partitions', index=1,
      number=2, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filter', full_name='voldemort.DeletePartitionEntriesRequest.filter', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_DELETEPARTITIONENTRIESRESPONSE = descriptor.Descriptor(
  name='DeletePartitionEntriesResponse',
  full_name='voldemort.DeletePartitionEntriesResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='count', full_name='voldemort.DeletePartitionEntriesResponse.count', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.DeletePartitionEntriesResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_INITIATEFETCHANDUPDATEREQUEST = descriptor.Descriptor(
  name='InitiateFetchAndUpdateRequest',
  full_name='voldemort.InitiateFetchAndUpdateRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='node_id', full_name='voldemort.InitiateFetchAndUpdateRequest.node_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='partitions', full_name='voldemort.InitiateFetchAndUpdateRequest.partitions', index=1,
      number=2, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='store', full_name='voldemort.InitiateFetchAndUpdateRequest.store', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filter', full_name='voldemort.InitiateFetchAndUpdateRequest.filter', index=3,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ASYNCOPERATIONSTATUSREQUEST = descriptor.Descriptor(
  name='AsyncOperationStatusRequest',
  full_name='voldemort.AsyncOperationStatusRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='request_id', full_name='voldemort.AsyncOperationStatusRequest.request_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_INITIATEREBALANCENODEREQUEST = descriptor.Descriptor(
  name='InitiateRebalanceNodeRequest',
  full_name='voldemort.InitiateRebalanceNodeRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='stealer_id', full_name='voldemort.InitiateRebalanceNodeRequest.stealer_id', index=0,
      number=2, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='donor_id', full_name='voldemort.InitiateRebalanceNodeRequest.donor_id', index=1,
      number=3, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='partitions', full_name='voldemort.InitiateRebalanceNodeRequest.partitions', index=2,
      number=4, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attempt', full_name='voldemort.InitiateRebalanceNodeRequest.attempt', index=3,
      number=5, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='deleteDonorPartitions', full_name='voldemort.InitiateRebalanceNodeRequest.deleteDonorPartitions', index=4,
      number=6, type=8, cpp_type=7, label=2,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='unbalanced_store', full_name='voldemort.InitiateRebalanceNodeRequest.unbalanced_store', index=5,
      number=7, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ASYNCOPERATIONSTATUSRESPONSE = descriptor.Descriptor(
  name='AsyncOperationStatusResponse',
  full_name='voldemort.AsyncOperationStatusResponse',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='request_id', full_name='voldemort.AsyncOperationStatusResponse.request_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='voldemort.AsyncOperationStatusResponse.description', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='voldemort.AsyncOperationStatusResponse.status', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='complete', full_name='voldemort.AsyncOperationStatusResponse.complete', index=3,
      number=4, type=8, cpp_type=7, label=2,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='voldemort.AsyncOperationStatusResponse.error', index=4,
      number=5, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_VOLDEMORTADMINREQUEST = descriptor.Descriptor(
  name='VoldemortAdminRequest',
  full_name='voldemort.VoldemortAdminRequest',
  filename='voldemort-admin.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='voldemort.VoldemortAdminRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='get_metadata', full_name='voldemort.VoldemortAdminRequest.get_metadata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='update_metadata', full_name='voldemort.VoldemortAdminRequest.update_metadata', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='update_partition_entries', full_name='voldemort.VoldemortAdminRequest.update_partition_entries', index=3,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fetch_partition_entries', full_name='voldemort.VoldemortAdminRequest.fetch_partition_entries', index=4,
      number=5, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='delete_partition_entries', full_name='voldemort.VoldemortAdminRequest.delete_partition_entries', index=5,
      number=6, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='initiate_fetch_and_update', full_name='voldemort.VoldemortAdminRequest.initiate_fetch_and_update', index=6,
      number=7, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='async_operation_status', full_name='voldemort.VoldemortAdminRequest.async_operation_status', index=7,
      number=8, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='initiate_rebalance_node', full_name='voldemort.VoldemortAdminRequest.initiate_rebalance_node', index=8,
      number=9, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import voldemort_client_pb2

_GETMETADATARESPONSE.fields_by_name['version'].message_type = voldemort_client_pb2._VERSIONED
_GETMETADATARESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_UPDATEMETADATAREQUEST.fields_by_name['versioned'].message_type = voldemort_client_pb2._VERSIONED
_UPDATEMETADATARESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_PARTITIONENTRY.fields_by_name['versioned'].message_type = voldemort_client_pb2._VERSIONED
_UPDATEPARTITIONENTRIESREQUEST.fields_by_name['partition_entry'].message_type = _PARTITIONENTRY
_UPDATEPARTITIONENTRIESREQUEST.fields_by_name['filter'].message_type = _VOLDEMORTFILTER
_UPDATEPARTITIONENTRIESRESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_FETCHPARTITIONENTRIESREQUEST.fields_by_name['filter'].message_type = _VOLDEMORTFILTER
_FETCHPARTITIONENTRIESRESPONSE.fields_by_name['partition_entry'].message_type = _PARTITIONENTRY
_FETCHPARTITIONENTRIESRESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_DELETEPARTITIONENTRIESREQUEST.fields_by_name['filter'].message_type = _VOLDEMORTFILTER
_DELETEPARTITIONENTRIESRESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_INITIATEFETCHANDUPDATEREQUEST.fields_by_name['filter'].message_type = _VOLDEMORTFILTER
_ASYNCOPERATIONSTATUSRESPONSE.fields_by_name['error'].message_type = voldemort_client_pb2._ERROR
_VOLDEMORTADMINREQUEST.fields_by_name['type'].enum_type = _ADMINREQUESTTYPE
_VOLDEMORTADMINREQUEST.fields_by_name['get_metadata'].message_type = _GETMETADATAREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['update_metadata'].message_type = _UPDATEMETADATAREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['update_partition_entries'].message_type = _UPDATEPARTITIONENTRIESREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['fetch_partition_entries'].message_type = _FETCHPARTITIONENTRIESREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['delete_partition_entries'].message_type = _DELETEPARTITIONENTRIESREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['initiate_fetch_and_update'].message_type = _INITIATEFETCHANDUPDATEREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['async_operation_status'].message_type = _ASYNCOPERATIONSTATUSREQUEST
_VOLDEMORTADMINREQUEST.fields_by_name['initiate_rebalance_node'].message_type = _INITIATEREBALANCENODEREQUEST

class GetMetadataRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETMETADATAREQUEST

class GetMetadataResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETMETADATARESPONSE

class UpdateMetadataRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATEMETADATAREQUEST

class UpdateMetadataResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATEMETADATARESPONSE

class PartitionEntry(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARTITIONENTRY

class UpdatePartitionEntriesRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATEPARTITIONENTRIESREQUEST

class UpdatePartitionEntriesResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATEPARTITIONENTRIESRESPONSE

class VoldemortFilter(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VOLDEMORTFILTER

class FetchPartitionEntriesRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FETCHPARTITIONENTRIESREQUEST

class FetchPartitionEntriesResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FETCHPARTITIONENTRIESRESPONSE

class DeletePartitionEntriesRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEPARTITIONENTRIESREQUEST

class DeletePartitionEntriesResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEPARTITIONENTRIESRESPONSE

class InitiateFetchAndUpdateRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INITIATEFETCHANDUPDATEREQUEST

class AsyncOperationStatusRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ASYNCOPERATIONSTATUSREQUEST

class InitiateRebalanceNodeRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INITIATEREBALANCENODEREQUEST

class AsyncOperationStatusResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ASYNCOPERATIONSTATUSRESPONSE

class VoldemortAdminRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VOLDEMORTADMINREQUEST

