/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class voldemort_store_leveldb_leveldbjni_DB */

#ifndef _Included_voldemort_store_leveldb_leveldbjni_DB
#define _Included_voldemort_store_leveldb_leveldbjni_DB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     voldemort_store_leveldb_leveldbjni_DB
 * Method:    _open
 * Signature: (Lvoldemort/store/leveldb/leveldbjni/DbOptions;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_voldemort_store_leveldb_leveldbjni_DB__1open
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DB
 * Method:    _put
 * Signature: (JLvoldemort/store/leveldb/leveldbjni/WriteOptions;[B[B)I
 */
JNIEXPORT jint JNICALL Java_voldemort_store_leveldb_leveldbjni_DB__1put
  (JNIEnv *, jclass, jlong, jobject, jbyteArray, jbyteArray);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DB
 * Method:    _delete
 * Signature: (JLvoldemort/store/leveldb/leveldbjni/WriteOptions;[B)I
 */
JNIEXPORT jint JNICALL Java_voldemort_store_leveldb_leveldbjni_DB__1delete
  (JNIEnv *, jclass, jlong, jobject, jbyteArray);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DB
 * Method:    _get
 * Signature: (JLvoldemort/store/leveldb/leveldbjni/ReadOptions;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_voldemort_store_leveldb_leveldbjni_DB__1get
  (JNIEnv *, jclass, jlong, jobject, jbyteArray);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DB
 * Method:    _write
 * Signature: (JLvoldemort/store/leveldb/leveldbjni/WriteOptions;Lvoldemort/store/leveldb/leveldbjni/WriteBatch;)I
 */
JNIEXPORT jint JNICALL Java_voldemort_store_leveldb_leveldbjni_DB__1write
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DB
 * Method:    _close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_voldemort_store_leveldb_leveldbjni_DB__1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DB
 * Method:    _newIterator
 * Signature: (JLvoldemort/store/leveldb/leveldbjni/ReadOptions;)J
 */
JNIEXPORT jlong JNICALL Java_voldemort_store_leveldb_leveldbjni_DB__1newIterator
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DB
 * Method:    _getProperty
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_voldemort_store_leveldb_leveldbjni_DB__1getProperty
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DB
 * Method:    _destroyDB
 * Signature: (Ljava/lang/String;Lvoldemort/store/leveldb/leveldbjni/DbOptions;)I
 */
JNIEXPORT jint JNICALL Java_voldemort_store_leveldb_leveldbjni_DB__1destroyDB
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DB
 * Method:    _compactRange
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_voldemort_store_leveldb_leveldbjni_DB__1compactRange
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
