/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class voldemort_store_leveldb_leveldbjni_WriteOptions */

#ifndef _Included_voldemort_store_leveldb_leveldbjni_WriteOptions
#define _Included_voldemort_store_leveldb_leveldbjni_WriteOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     voldemort_store_leveldb_leveldbjni_WriteOptions
 * Method:    _new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_voldemort_store_leveldb_leveldbjni_WriteOptions__1new
  (JNIEnv *, jclass);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_WriteOptions
 * Method:    _setSync
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_voldemort_store_leveldb_leveldbjni_WriteOptions__1setSync
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
