/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class voldemort_store_leveldb_leveldbjni_ReadOptions */

#ifndef _Included_voldemort_store_leveldb_leveldbjni_ReadOptions
#define _Included_voldemort_store_leveldb_leveldbjni_ReadOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     voldemort_store_leveldb_leveldbjni_ReadOptions
 * Method:    _new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_voldemort_store_leveldb_leveldbjni_ReadOptions__1new
  (JNIEnv *, jclass);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_ReadOptions
 * Method:    _setFillCache
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_voldemort_store_leveldb_leveldbjni_ReadOptions__1setFillCache
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_ReadOptions
 * Method:    _setVerifyChecksums
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_voldemort_store_leveldb_leveldbjni_ReadOptions__1setVerifyChecksums
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
