/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class voldemort_store_leveldb_leveldbjni_DbOptions */

#ifndef _Included_voldemort_store_leveldb_leveldbjni_DbOptions
#define _Included_voldemort_store_leveldb_leveldbjni_DbOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbOptions
 * Method:    _setCreateIfMissing
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_voldemort_store_leveldb_leveldbjni_DbOptions__1setCreateIfMissing
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbOptions
 * Method:    _setErrorIfExists
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_voldemort_store_leveldb_leveldbjni_DbOptions__1setErrorIfExists
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbOptions
 * Method:    _setParanoidChecks
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_voldemort_store_leveldb_leveldbjni_DbOptions__1setParanoidChecks
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbOptions
 * Method:    _setWriteBufferSize
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_voldemort_store_leveldb_leveldbjni_DbOptions__1setWriteBufferSize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbOptions
 * Method:    _setMaxOpenFile
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_voldemort_store_leveldb_leveldbjni_DbOptions__1setMaxOpenFile
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbOptions
 * Method:    _setLRUBlockCache
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_voldemort_store_leveldb_leveldbjni_DbOptions__1setLRUBlockCache
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbOptions
 * Method:    _setBlockSize
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_voldemort_store_leveldb_leveldbjni_DbOptions__1setBlockSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbOptions
 * Method:    _setBlockRestartInterval
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_voldemort_store_leveldb_leveldbjni_DbOptions__1setBlockRestartInterval
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbOptions
 * Method:    _setCompressionType
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_voldemort_store_leveldb_leveldbjni_DbOptions__1setCompressionType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbOptions
 * Method:    _new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_voldemort_store_leveldb_leveldbjni_DbOptions__1new
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
