/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class voldemort_store_leveldb_leveldbjni_DbIterator */

#ifndef _Included_voldemort_store_leveldb_leveldbjni_DbIterator
#define _Included_voldemort_store_leveldb_leveldbjni_DbIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbIterator
 * Method:    _seekToFirst
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_voldemort_store_leveldb_leveldbjni_DbIterator__1seekToFirst
  (JNIEnv *, jclass, jlong);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbIterator
 * Method:    _seek
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_voldemort_store_leveldb_leveldbjni_DbIterator__1seek
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbIterator
 * Method:    _next
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_voldemort_store_leveldb_leveldbjni_DbIterator__1next
  (JNIEnv *, jclass, jlong);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbIterator
 * Method:    _valid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_voldemort_store_leveldb_leveldbjni_DbIterator__1valid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbIterator
 * Method:    _key
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_voldemort_store_leveldb_leveldbjni_DbIterator__1key
  (JNIEnv *, jclass, jlong);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbIterator
 * Method:    _value
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_voldemort_store_leveldb_leveldbjni_DbIterator__1value
  (JNIEnv *, jclass, jlong);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbIterator
 * Method:    _status
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_voldemort_store_leveldb_leveldbjni_DbIterator__1status
  (JNIEnv *, jclass, jlong);

/*
 * Class:     voldemort_store_leveldb_leveldbjni_DbIterator
 * Method:    _close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_voldemort_store_leveldb_leveldbjni_DbIterator__1close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
